# Pre-commit hooks configuration
# See https://pre-commit.com for more information

default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit]

repos:
  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]
        files: ^(scripts|tests)/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]
        files: ^(scripts|tests)/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        files: ^(scripts|tests)/.*\.py$

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        files: ^scripts/.*\.py$
        additional_dependencies: [types-PyYAML, types-click]
        args: [--ignore-missing-imports, --disallow-untyped-defs]

  # Terraform formatting and validation (requires terraform to be installed)
  # Uncomment when terraform, terraform-docs, and tflint are installed
  # - repo: https://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.86.0
  #   hooks:
  #     - id: terraform_fmt
  #       args: [--args=-recursive]
  #     - id: terraform_validate
  #       args: [--args=-json]
  #     - id: terraform_docs
  #       args: [--args=--output-file README.md]
  #     - id: terraform_tflint
  #       args: [--args=--only=terraform_deprecated_interpolation]

  # Security scanning
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.436
    hooks:
      - id: checkov
        args: [--framework=terraform, --quiet]
        files: \.tf$
        exclude: \.terraform/

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
        exclude: \.md$
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first

  # Conventional commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, style, refactor, test, chore, ci]

  # Security scanning - bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: [-c, .bandit, -r]
        files: ^scripts/.*\.py$

# Configuration for specific tools
ci:
  autofix_prs: true
  autoupdate_schedule: monthly
